# Generated by Django 4.2.1 on 2024-01-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.FileField(help_text='Устанавливается автоматически', upload_to='chat_history', verbose_name='История чата')),
                ('last_message', models.CharField(help_text='Устанавливается автоматически', max_length=300, verbose_name='Последнее сообщение')),
                ('state', models.CharField(choices=[(0, 'Новое сообщение'), (1, 'В работе'), (2, 'Отказано'), (3, 'Срочно'), (4, 'Помощь предоставлена')], default=0, verbose_name='Состояние чата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель комнаты')),
            ],
        ),
    ]
