# Generated by Django 4.2.1 on 2024-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message_remove_chatroom_history_chatroom_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.CharField(help_text='Устанавливается автоматически', max_length=300, null=True, verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='support.message'),
        ),
    ]
