# Generated by Django 4.2.1 on 2024-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_chatroom_last_message_alter_chatroom_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='state',
            field=models.CharField(choices=[('0', 'Новое сообщение'), ('1', 'В работе'), ('2', 'Отказано'), ('3', 'Срочно'), ('4', 'Помощь предоставлена')], default=0, verbose_name='Состояние чата'),
        ),
    ]
