# Generated by Django 4.2.1 on 2024-01-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
    ]
