# Generated by Django 4.2.1 on 2023-11-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CharPage', '0005_alter_charmodel_char_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название талантов')),
                ('url', models.URLField(max_length=250)),
                ('char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharPage.charmodel', verbose_name='Привязанные персонажи')),
            ],
        ),
    ]
