# Generated by Django 4.2.1 on 2023-11-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentsmodel',
            options={'verbose_name': 'Талантам', 'verbose_name_plural': 'Таланты'},
        ),
    ]
