# Generated by Django 4.2.1 on 2023-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talants', '0002_alter_talentsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_class',
            field=models.CharField(default='', max_length=32, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_spec',
            field=models.CharField(default='e', max_length=32, verbose_name='Спецификация'),
        ),
    ]
