# Generated by Django 4.2.1 on 2023-11-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0005_alter_charmodel_char_class'),
        ('talants', '0003_talentsmodel_talent_class_talentsmodel_talent_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentsmodel',
            name='char',
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_spec',
            field=models.CharField(default='', max_length=32, verbose_name='Спецификация'),
        ),
        migrations.AddField(
            model_name='talentsmodel',
            name='char',
            field=models.ManyToManyField(null=True, to='CharPage.charmodel', verbose_name='Привязанные персонажи'),
        ),
    ]
