# Generated by Django 4.2.1 on 2023-11-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talants', '0004_remove_talentsmodel_char_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentsmodel',
            name='char',
        ),
    ]
