# Generated by Django 4.2.1 on 2023-11-09 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=45, verbose_name='Id комнаты')),
                ('last_update_time', models.DateTimeField(verbose_name='Время последнего изменения')),
                ('allow_edit', models.BooleanField(verbose_name='Разрешить редактирование')),
                ('race', models.IntegerField(verbose_name='Раса')),
                ('gender', models.IntegerField(verbose_name='Пол')),
                ('items', models.CharField(blank=True, max_length=300, verbose_name='Экипировка')),
                ('face', models.CharField(max_length=150, verbose_name='Внешность')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель комнаты')),
            ],
            options={
                'verbose_name': 'Персонажу',
                'verbose_name_plural': 'Персонажи',
            },
        ),
    ]
