# Generated by Django 4.2.1 on 2023-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0002_charmodel_creating'),
    ]

    operations = [
        migrations.AddField(
            model_name='charmodel',
            name='char_class',
            field=models.CharField(default='', max_length=32, verbose_name='Класс персонажа'),
        ),
        migrations.AddField(
            model_name='charmodel',
            name='char_name',
            field=models.CharField(default='', max_length=32, verbose_name='Имя персонажа'),
        ),
        migrations.AddField(
            model_name='charmodel',
            name='proffesions',
            field=models.CharField(default='', max_length=32, verbose_name='Профессии'),
        ),
    ]
