# Generated by Django 4.2.1 on 2023-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0003_charmodel_char_class_charmodel_char_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmodel',
            name='char_class',
            field=models.CharField(default='Разбойник', max_length=32, verbose_name='Класс персонажа'),
        ),
    ]
