# Generated by Django 4.2.1 on 2023-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0004_alter_charmodel_char_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmodel',
            name='char_class',
            field=models.CharField(default='', max_length=32, verbose_name='Класс персонажа'),
        ),
    ]
