# Generated by Django 4.2.1 on 2023-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0006_charmodel_talents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmodel',
            name='items',
            field=models.CharField(blank=True, max_length=512, verbose_name='Экипировка'),
        ),
    ]
