# Generated by Django 4.2.1 on 2023-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0007_alter_charmodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmodel',
            name='items',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Экипировка'),
        ),
    ]
