# Generated by Django 4.2.1 on 2024-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharPage', '0008_alter_charmodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmodel',
            name='proffesions',
            field=models.CharField(default='[0,0]', max_length=32, verbose_name='Профессии'),
        ),
    ]
