# Generated by Django 4.2.1 on 2023-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
