# Generated by Django 4.2.1 on 2023-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0003_remove_addon_active_addon_is_published_addon_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='file',
            field=models.FileField(null=True, upload_to='addons_file', verbose_name='Файл с аддоном'),
        ),
    ]
