# Generated by Django 4.2.1 on 2023-10-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0004_addon_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='images',
        ),
        migrations.CreateModel(
            name='AddonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='addons_images', verbose_name='Картинка аддона')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='addons.addon')),
            ],
        ),
    ]
