# Generated by Django 4.2.1 on 2023-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0005_remove_addon_images_addonimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='category',
        ),
        migrations.AddField(
            model_name='addon',
            name='ccc',
            field=models.ManyToManyField(related_name='a_category', to='addons.addoncategory', verbose_name='Категория'),
        ),
    ]
