# Generated by Django 4.2.1 on 2023-10-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0007_rename_ccc_addon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена'),
        ),
    ]
