# Generated by Django 4.2.1 on 2023-11-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0008_alter_addon_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatible_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='Версия игры')),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='author',
            field=models.CharField(default='Jojin', max_length=32),
        ),
        migrations.AddField(
            model_name='addon',
            name='version',
            field=models.ManyToManyField(to='addons.compatible_versions', verbose_name='Версия игры:'),
        ),
    ]
