# Generated by Django 4.2.1 on 2024-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0010_alter_addon_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=models.CharField(verbose_name='Краткое описание аддона'),
        ),
    ]
