# Generated by Django 4.2.1 on 2023-12-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название класса')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название способа связи')),
            ],
        ),
        migrations.CreateModel(
            name='FractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название фракции')),
            ],
        ),
        migrations.CreateModel(
            name='MentorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Никнейм ментора')),
                ('telegram_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название сервера')),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название услуги')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Тип услуги')),
                ('server', models.CharField(max_length=64, verbose_name='Сервер')),
                ('fraction', models.CharField(max_length=32, verbose_name='Сторона')),
                ('class_name', models.CharField(max_length=32, verbose_name='Класс')),
                ('mentor', models.CharField(max_length=32, verbose_name='Ментор')),
                ('communication', models.CharField(max_length=32, verbose_name='Способ связи')),
                ('username', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('comment', models.CharField(max_length=264, verbose_name='Дополнительный комментарий')),
                ('time_of_create', models.DateTimeField(verbose_name='Время создания услуги')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель услуги')),
            ],
            options={
                'verbose_name': 'Услуге',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
