# Generated by Django 4.2.1 on 2023-12-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmodel',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='communicationmodel',
            options={'verbose_name': 'Способ связи', 'verbose_name_plural': 'Способы связи'},
        ),
        migrations.AlterModelOptions(
            name='fractionmodel',
            options={'verbose_name': 'Фракцию', 'verbose_name_plural': 'Фракции'},
        ),
        migrations.AlterModelOptions(
            name='mentormodel',
            options={'verbose_name': 'Ментора', 'verbose_name_plural': 'Менторы'},
        ),
        migrations.AlterModelOptions(
            name='servermodel',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AlterModelOptions(
            name='typemodel',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуги'},
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='comment',
            field=models.CharField(max_length=264, null=True, verbose_name='Дополнительный комментарий'),
        ),
    ]
