FROM python:3.11.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /mysite
WORKDIR /mysite

COPY requirements.txt /mysite/

RUN pip install --upgrade pip && pip install -r requirements.txt

ADD . /mysite/