# Generated by Django 4.2.1 on 2024-01-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(max_length=32, null=True, verbose_name='Discord'),
        ),
    ]
