# Generated by Django 4.2.1 on 2024-01-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
    ]
